/*
** This file was generated by 4tH
** Copyright 1997,2010 by J.L. Bezemer
*/

#ifdef USRLIB4TH
#include <4th.h>
#else
#include "4th.h"
#endif

#include <stdlib.h>


static dict CodeSegment [] = {
  {'\x1d',           7L}, {'\x02',           0L}, {'\x05',           0L}, 
  {'\x02',           0L}, {'\x32',           1L}, {'\x06',           0L}, 
  {'\x02',           0L}, {'\x41',           0L}, {'\x47',           0L}
};

static char StringSegment [] = {
  '\x48', '\x65', '\x6c', '\x6c', '\x6f', '\x00'
};

static Hcode Object = {
  9, CodeSegment, 6U, StringSegment, NULL, NULL, 0, 0U, 0U, 0, 0, TRUE
};


#ifndef ARCHAIC
  int main (int argc, char **argv)
#else
  int main (argc, argv) int argc; char **argv;
#endif

{
  cell   Result;                       /* holds the result of the program */

  fflush (stderr);                     /* flush any messages */
                                       /* now execute it */
  Result = exec_4th (&Object, argc, argv, 0);

  fflush (stdout);

  if (Object.ErrNo)                    /* show exit messages */
     fprintf (stderr, "Exiting; word %u: %s\n", Object.ErrLine,
              errs_4th [Object.ErrNo]);
  else
     if (Result != CELL_MIN)
        fprintf (stderr, "Exiting; result: %ld\n", Result);

  return (Object.ErrNo ? EXIT_FAILURE : EXIT_SUCCESS);
}
