1 PRINT "TRAIN"
2 PRINT "CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY"
3 PRINT: PRINT: PRINT
4 PRINT "TIME - SPEED DISTANCE EXERCISE": PRINT
10 C=RND(25)+40
15 D=RND(15)+5
20 T=RND(19)+20
25 PRINT "A CAR TRAVELING ";C;" MPH CAN MAKE A CERTAIN TRIP IN"
30 PRINT D;" HOURS LESS THAN A TRAIN TRAVELING AT ";T;" MPH."
35 INPUT "HOW LONG DOES THE TRIP TAKE BY CAR? ";A
40 V=D*T/(C-T)
50 E=((((V-A)*200)/A)+1)/2 : IF E<0 THEN E=-E
55 IF E>5 THEN GOTO 70
60 PRINT "GOOD! ANSWER WITHIN ";E;" PERCENT."
65 GOTO 80
70 PRINT "SORRY. YOU WERE OFF BY ";E;" PERCENT."
80 PRINT "CORRECT ANSWER IS ";V;" HOURS."
90 PRINT
95 INPUT "ANOTHER PROBLEM (YES=1 OR NO=0)? ";A
110 IF A#0 THEN GOTO 10
999 END